### PR TITLE
iOS shortcut guide

### PR DESCRIPTION
**Pull request by wraithy**
added ios-shortcuts.md to the uploader guides and included images to show how the shortcut works.

### CODE REVIEW

**Review by TacticalTechJay — DISMISSED** [review]
Looks good to me!
@diced can merge this one.
(The base and fork match. There should be no issue merging this.)

**Comment by TacticalTechJay** [comment]
Something that I should mention to @wraithdotcat though. You'll need to get your commits signed before this can get merged.

**Comment by wraithy** [comment]
I am not sure if I need to sign all of my previous commits but I managed to sign the latest ones. I was testing to see if I could sign all of the previous commits but it doesn't look like it worked. If I need to close this PR and open a new one, I will do that instead since these changes are easy to move.

**Review by diced — APPROVED** [review]

**Comment by diced** [comment]
Looks good, hope this works for iOS users as I can't test.

**Pull request merged**
